name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build the React App
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ 1//09WDhfRMk3-BgCgYIARAAGAkSNwF-L9Irvh3q_63bJDx7o7S6O7u4-LFo7_I5w4cliYQnngAZxKjKzqKxVkyrnjJp8EKHCfz3hq0 }}
        env:
          FIREBASE_AUTH_TOKEN: ${{ 1//09WDhfRMk3-BgCgYIARAAGAkSNwF-L9Irvh3q_63bJDx7o7S6O7u4-LFo7_I5w4cliYQnngAZxKjKzqKxVkyrnjJp8EKHCfz3hq0 }}
